#!/usr/bin/env bash

leftwm command "UnloadTheme"
# add kill commands for anything you launched in the 'up' script e.g.:
pkill picom
compton -b --config $HOME/.config/leftwm/compton.conf

eww reload
# pkill polybar
# pkill compton
