#!/usr/bin/env bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"


#down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down



#boot compton or picom if it exists
#and picom installed fork of picom for compton -> picom-arian8j2-git or picom-jonaburg-git
if [ -x "$(command -v compton)" ]; then
	compton -b --config $HOME/.config/leftwm/themes/deviuspro_leftwm/compton.conf
fi
#elif [ -x "$(command -v picom)" ]; then
 # picom &> /dev/null & 
#fi

#set the theme.{toml, ron} config
leftwm-command "LoadTheme $SCRIPTPATH/theme.ron"

if [ -x "$(command -v eww)" ]; then
	eww open bar
fi

#set feh or nitrogen
if [ -x "$(command -v feh)" ]; then
	feh --bg-scale .config/Wallpaper/exquisito.* &
elif [ -x "$(command -v nitrogen)" ]; then
	nitrogen --restore &
fi


